### ISSUE TITLE
Random error "GD2 is not missing constant GD2FFI!"

### ISSUE THREAD

**Issue by dimir** [amardaxini/rchart#10]
Sometimes (about 1 from 5 times) I get this strange error in my rails app:

ArgumentError in MyController#myaction

GD2 is not missing constant GD2FFI!

I do not understand the meaning of it. The stack trace from rails:

http://pastebin.com/dgdz2F0K

**Comment by amardaxini** [comment]
It's issue with gd2-ffij binding this is fixed in version 0.0.5 .I have updated gem and it's dependency to 2.0.8,check it out.

Thanks,

**Comment by dimir** [comment]
I don't get this error in 2.0.8, thanks!
