### ISSUE TITLE
Rchart hangs on draw_scale() with point [0,1,0]

### ISSUE THREAD

**Issue by dimir** [amardaxini/rchart#11]
How to reproduce:

1) clone git://github.com/amardaxini/rchart_examples.git
2) edit example9.rb and remove serie2 and serie3
3) edit serie 1 point data to be [0,1,0]
4) run: ruby example9.rb

This will hang the process in draw_scale() with ruby consuming almost 100% CPU.

**Comment by amardaxini** [comment]
Fixed in version 2.0.9

**Comment by dimir** [comment]
Thanks, indeed fixed in 2.0.9 .
