### ISSUE TITLE
period before percentage

### ISSUE THREAD

**Issue by runa** [amardaxini/rchart#15]
Hello, I was wondering what's [this period (".")](https://github.com/amardaxini/rchart/blob/rchart-gd2/lib/pie_chart.rb#L65) before the value when using Rchart::PIE_PERCENTAGE_LABEL

``` ruby
          caption  = i_labels[key].to_s+"\r\n"+"."+((value * (10**decimals) * splice_percent)/(10**decimals)).round.to_s+"%"
```

It generates some confusing "Foo .99%" labels, which make no sense to me (it should be 99%, not .99%)

pd: it's me or [this line](https://github.com/amardaxini/rchart/blob/rchart-gd2/lib/pie_chart.rb#L64) is duplicated [here](https://github.com/amardaxini/rchart/blob/rchart-gd2/lib/pie_chart.rb#L66) ?

**Comment by nikhilthombare** [comment]
Here I fixed this issue #16
