### ISSUE TITLE
draw_xy_scale doesn't handle a large x scale

### ISSUE THREAD

**Issue by mlsquires** [amardaxini/rchart#4]
branch: rchart-gd2
test: test_scaling.rb (new test case)
file: scale.rb
method: draw_xy_scale

Repro steps:
1. create a dataset with a large x scale (e.g., 0..70000) - it doesn't have to have many points - the test case uses only 4 points but I saw this bug with 3000 data points
2. call draw_xy_plot_graph
3. See that all points are at the 'x=0' location

This line is the culprit:
@x_division_ratio  = ( @g_area_x2 - @g_area_x1 ) / x_data_range

If x_data_range is high that results in an x_division_ratio of zero.

The fix is easy:
@x_division_ratio  = ( @g_area_x2.to_f - @g_area_x1.to_f ) / x_data_range.to_f

I can generate a patch with the fix and the test case if you like.

**Comment by amardaxini** [comment]
Sure you can send me an pull request
