### ISSUE TITLE
Missing usage example

### ISSUE THREAD

**Issue by dimir** [amardaxini/rchart#7]
E. g. what to put to controller, what to view etc.

**Comment by amardaxini** [comment]
Hi,
I have added sample repo  for rails you can refer https://github.com/amardaxini/rails-rchart-demo

**Comment by dimir** [comment]
Thanks, it worked for me now!

Although I had to enable 'therubyracer' gem in Gemfile and also fix something in the code for the server to start: http://pastebin.com/4tfdp8CF

Perhaps this is not supported by my rails version?

rails-rchart-demo$ gem list rails

**\* LOCAL GEMS ***

rails (3.2.6, 3.0.8, 3.0.3)

In any case, I suggest this be mentioned in the README file or something. :-)
