### ISSUE TITLE
2.0.5 is broken

### ISSUE THREAD

**Issue by dimir** [amardaxini/rchart#9]
Cannot use version 2.0.5, when starting rails I get:

$ rails s
/var/lib/gems/1.8/gems/rchart-2.0.5/lib/rchart.rb:1:in `require': no such file to load -- GD (LoadError)
        from /var/lib/gems/1.8/gems/rchart-2.0.5/lib/rchart.rb:1
        from /var/lib/gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:68:in`require'
        from /var/lib/gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:68:in `require'
        from /var/lib/gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:66:in`each'
        from /var/lib/gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:66:in `require'
        from /var/lib/gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:55:in`each'
        from /var/lib/gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:55:in `require'
        from /var/lib/gems/1.8/gems/bundler-1.0.15/lib/bundler.rb:120:in`require'
        from /home/vl/git/upis/web/config/application.rb:7
        from /var/lib/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:28:in `require'
        from /var/lib/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:28
        from /var/lib/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:27:in`tap'
        from /var/lib/gems/1.8/gems/railties-3.0.3/lib/rails/commands.rb:27
        from script/rails:6:in `require'
        from script/rails:6

If I remove 2.0.5 and install 2.0.4 everything works fine. As soon as I install 2.0.5 I get this error.

**Comment by amardaxini** [comment]
Updated gem with use 2.0.6

**Comment by dimir** [comment]
Thanks.
